language: go

go:
  - 1.9

addons:
  mariadb: '10.0'

services:
  - postgresql
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - go install && go generate demo/*.go
  - JDRIVER="sqlite3" JDSN="db.sql" go test -v demo/*.go
  - JDRIVER="mysql" JDSN="root:@/test?parseTime=true" go test -v demo/*.go
  - JDRIVER="postgres" JDSN="postgres://travis:@localhost/travis_ci_test" go test -v demo/*.go
